# .streamlit/secrets.toml

GEMINI_API_KEY = "AIzaSyAVxllAeb7WvkI9xZ2rC22LkM-mnmI20AM"

# You can add other secrets too, if needed for other parts of your app
# ANOTHER_API_KEY = "another_secret_value"
# DATABASE_PASSWORD = "super_secure_password123"
#GCD/CLOUD = "##########################"
